//
// Created by tommy on 16.06.17.
//

#ifndef UNEMPLOYED_MORRONS_GOOUTOFQUEUEMESSAGE_H
#define UNEMPLOYED_MORRONS_GOOUTOFQUEUEMESSAGE_H


class GoOutOfQueueMessage {

};


#endif //UNEMPLOYED_MORRONS_GOOUTOFQUEUEMESSAGE_H
